#!/usr/bin/env python3
"""Pin wrapper for the New Juice top: connects every port of `top` (src/top.v)
to pin[N] of the QN88 package exactly as src/top.cst says, so the bench drives
the design through the board model by PIN NUMBER (like MoonTANG's
tools/sim/gen_pin_wrapper.py, which this follows; New Juice declares its ports
without `wire`). Differential pairs `IO_LOC "x_p" a,b;` give x_p -> a, x_n -> b.
The embedded-SDRAM ports (names with 'sdram') are passed through.

Usage: gen_pins_nj.py <top.v> <top.cst> <out.v>
"""
import re
import sys

top_v, cst, out = sys.argv[1:4]
NL = chr(10)

src = open(top_v, encoding='utf-8').read()
i = src.index('module top')
body = src[i:]
# port list: from the '(' that follows the parameter block to the first ');'
j = body.index(')', body.index('#(')) + 1          # end of #( ... )
k = body.index('(', j)
hdr = body[k + 1:body.index(');', k)]
ports = []
for m in re.finditer(r'^\s*(input|output|inout)\s+(?:wire\s+)?(\[(\d+):0\])?\s*(\w+)', hdr, re.M):
    ports.append((m.group(1), m.group(4), int(m.group(3)) + 1 if m.group(3) else 1))
assert ports, 'no ports found'

loc = {}
for m in re.finditer(r'^\s*IO_LOC\s+"(\w+)(?:\[(\d+)\])?"\s+(\d+)(?:\s*,\s*(\d+))?\s*;',
                     open(cst, encoding='utf-8').read(), re.M):
    name, idx = m.group(1), int(m.group(2)) if m.group(2) is not None else None
    assert (name, idx) not in loc, f'duplicate {name}[{idx}]'
    loc[(name, idx)] = int(m.group(3))
    if m.group(4):
        assert name.endswith('_p')
        loc[(name[:-2] + '_n', idx)] = int(m.group(4))
pins = list(loc.values())
assert len(pins) == len(set(pins)), 'two signals share a pin'

lines, sdram, used, trans = [], [], set(), []
for d, name, w in ports:
    if 'sdram' in name:
        sdram.append((d, name, w))
        lines.append(f'        .{name}({name})')
        continue
    if w == 1:
        assert (name, None) in loc, f'{name} has no IO_LOC'
        used.add((name, None))
        if d == 'inout':
            trans.append((name, 1, [loc[(name, None)]]))
            lines.append(f'        .{name}(w_{name}[0])')
        else:
            lines.append(f'        .{name}(pin[{loc[(name, None)]}])')
        continue
    for b in range(w):
        assert (name, b) in loc, f'{name}[{b}] has no IO_LOC'
        used.add((name, b))
    if d == 'inout':
        trans.append((name, w, [loc[(name, b)] for b in range(w)]))
        lines.append(f'        .{name}(w_{name})')
    else:
        bits = [f'pin[{loc[(name, b)]}]' for b in range(w - 1, -1, -1)]
        lines.append(f'        .{name}({{{", ".join(bits)}}})')
left = set(loc) - used
assert not left, f'IO_LOC without a port: {sorted(left, key=str)}'

o = [f'// GENERATED by gen_pins_nj.py from {cst} - do not edit.',
     '`timescale 1ns/1ps',
     'module nj_pins (']
plist = ['    inout wire [88:1] pin']
for d, name, w in sdram:
    rng = f'[{w-1}:0] ' if w > 1 else ''
    plist.append(f'    {d} wire {rng}{name}')
o.append((',' + NL).join(plist))
o.append(');')
for name, w, pins_ in trans:
    o.append(f'    wire [{w-1}:0] w_{name};')
    for b, pn in enumerate(pins_):
        o.append(f'    tran t_{name}_{b} (w_{name}[{b}], pin[{pn}]);')
o.append('    top u_top (')
o.append((',' + NL).join(lines))
o.append('    );')
o.append('endmodule')
with open(out, 'w', encoding='utf-8', newline=NL) as f:
    f.write(NL.join(o) + NL)
print(f'{out}: {len(used)} pin signals, {len(sdram)} SDRAM ports')
